# Generated by Django 3.1.3 on 2021-01-09 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmanager',
            name='eula_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sessionmanager',
            name='eula_version',
            field=models.CharField(default='eula-v1-09-01-2021', max_length=100),
        ),
    ]
