# Generated by Django 3.1.3 on 2020-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='post_process_status',
            field=models.CharField(choices=[('invitation processed', 'invitation processed'), ('not processed', 'not processed'), ('registration processed', 'registration processed')], default='not processed', max_length=50),
        ),
    ]
