# Generated by Django 3.1.3 on 2021-01-09 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0002_auto_20210109_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmanager',
            name='privacy_policy_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sessionmanager',
            name='privacy_policy_version',
            field=models.CharField(default='privacy-policy-v1-09-01-2021', max_length=100),
        ),
    ]
